name: Release

on:
  push:
    branches:
      - main  # Trigger releases on pushes to the main branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history is required for semantic-release

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"
          # Optionally configure poetry to use the system virtualenv:
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}           # Your GitHub PAT (with repo scope)
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}     # Your PyPI username
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}     # Your PyPI API token
          # Optionally, if testing on Test PyPI, use:
          # PYPI_REPOSITORY_URL: "https://test.pypi.org/legacy/"
        run: poetry run semantic-release publish