name: Semantic Release

on:
  push:
    branches:
      - main  # Run only on the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for semantic-release to analyze commit history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install python-semantic-release build

      - name: Build package  # Ensure dist/* is generated
        run: python -m build

      - name: Run semantic release
        id: release  # <-- Added ID to reference outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # <-- Fixed token name
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_REPOSITORY_URL: "https://test.pypi.org/legacy/"  # <-- Publishes to TestPyPI
        run: |
          semantic-release -vv publish

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        if: steps.release.outputs.released == 'true'